### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by untitaker** [untitaker/python-atomicwrites#1]
See https://github.com/untitaker/rust-atomicwrites/issues/3

**Comment by untitaker** [comment]
This is now implemented, but untested. Are there any good CI services for Windows?

**Comment by RaitoBezarius** [comment]
You should try AppVeyor!

**Comment by untitaker** [comment]
Yeah I'm currently trying it out. Slowly fixing stuff in #3, but too lazy to get a Windows VM properly set up.

**Comment by untitaker** [comment]
This works now, although I am not sure how to test atomicity properly.
