### ISSUE TITLE
fsync after rename/move

### ISSUE THREAD

**Issue by Unrud** [untitaker/python-atomicwrites#12]
On POSIX it's possible to fsync the directory, to ensure that the new file names are written to disk.
I think on Windows it's necessary to open the new (target) file and fsync it.

**Comment by untitaker** [comment]
POSIX: You appear to be correct.

Windows: Off the bat I can't find any information in either direction (neither proving nor disproving your claim)

I wonder if we should introduce an option to disable fsync calls for situations where performance is more important and just atomicity (not much more) is required.

On 14 July 2016 08:32:50 CEST, Unrud notifications@github.com wrote:

> On POSIX it's possible to fsync the directory, to ensure that the new
> file names are written to disk.
> I think on Windows it's necessary to open the new (target) file and
> fsync it.
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/untitaker/python-atomicwrites/issues/12

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Unrud** [comment]
> I wonder if we should introduce an option to disable fsync calls for situations where performance is more important and just atomicity (not much more) is required.

You will loose atomicity if you do that. It may be possible that the new file name gets written to disk before the data is fully written. This only provides protection against errors where writing to the temporary file fails (e.g. out of disk space).

If you want to include fsync'ing of the directory, you could make it optional. Maybe durability is out of scope.

**Comment by untitaker** [comment]
Oh, I didn't really think about that (I sort of assumed that closing the file would suffice as well).

I guess though the fsync you propose could be expendable (in some situations)?

On 15 July 2016 11:26:41 CEST, Unrud notifications@github.com wrote:

> > I wonder if we should introduce an option to disable fsync calls for
> > situations where performance is more important and just atomicity (not
> > much more) is required.
> 
> You will loose atomicity if you do that. It may be possible that the
> new file name gets written to disk before the data is fully written.
> This only provides protection against errors where writing to the
> temporary file fails (e.g. out of disk space).
> 
> If you want to include fsync'ing of the directory, you could make it
> optional. Maybe durability is out of scope.
> 
> ---
> 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/untitaker/python-atomicwrites/issues/12#issuecomment-232904653

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by untitaker** [comment]
I guess though the fsync you propose could be expendable?

On 15 July 2016 11:26:41 CEST, Unrud <notifications@github.com> wrote:
>> I wonder if we should introduce an option to disable fsync calls for
>situations where performance is more important and just atomicity (not
>much more) is required.
>
>You will loose atomicity if you do that. It may be possible that the
>new file name gets written to disk before the data is fully written.
>This only provides protection against errors where writing to the
>temporary file fails (e.g. out of disk space).
>
>If you want to include fsync'ing of the directory, you could make it
>optional. Maybe durability is out of scope.
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/python-atomicwrites/issues/12#issuecomment-232904653

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Unrud** [comment]
> Windows: Off the bat I can't find any information in either direction (neither proving nor disproving your claim) 

I can't either, I guess I remembered that wrong. The **MOVEFILE_WRITE_THROUGH** flag for [MoveFileEx](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365240%28v=vs.85%29.aspx)  is used in the code, that problem is already solved for Windows. Sorry.

> I sort of assumed that closing the file would suffice as well

Dirty buffer cache pages and metadata are not written to disk when the file is closed.

> I guess though the fsync you propose could be expendable (in some situations)?

I can't think of an example. It's expendable if you don't need durability.

**Comment by Unrud** [comment]
> The **MOVEFILE_WRITE_THROUGH** flag for [MoveFileEx](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365240%28v=vs.85%29.aspx) is used in the code, that problem is already solved for Windows.

Actually I'm not sure about this. It only explicitly mentions that data is synced if the file is copied from a different volume. I guess that this doesn't include meta data as other file operations that only work within one volume don't have a flag like this: [ReplaceFile](https://msdn.microsoft.com/de-de/library/windows/desktop/aa365512%28v=vs.85%29.aspx), [DeleteFile](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363915%28v=vs.85%29.aspx)

Some of the failure modes of [ReplaceFile](https://msdn.microsoft.com/de-de/library/windows/desktop/aa365512%28v=vs.85%29.aspx) also suggest that the operations is not atomic. I guess this also applies to [MoveFileEx](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365240%28v=vs.85%29.aspx) if the flag **MOVEFILE_REPLACE_EXISTING** is used and target already exists.

**Comment by untitaker** [comment]
MoveFileEx is not documented to be atomic anyway, I'm just relying on a posting by a MS employee in the now-removed comments section of MSDN.

On 2 August 2016 08:55:23 CEST, Unrud notifications@github.com wrote:

> > The **MOVEFILE_WRITE_THROUGH** flag for
> > [MoveFileEx](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365240%28v=vs.85%29.aspx)
> > is used in the code, that problem is already solved for Windows.
> 
> Actually I'm not sure about this. It only explicitly mentions that data
> is synced if the file is copied from a different volume. I guess that
> this doesn't include meta data as other file operations that only work
> within one volume don't have a flag like this:
> [ReplaceFile](https://msdn.microsoft.com/de-de/library/windows/desktop/aa365512%28v=vs.85%29.aspx),
> [DeleteFile](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363915%28v=vs.85%29.aspx)
> 
> Some of the failure modes of
> [ReplaceFile](https://msdn.microsoft.com/de-de/library/windows/desktop/aa365512%28v=vs.85%29.aspx)
> also suggest that the operations is not atomic. I guess this also
> applies to
> [MoveFileEx](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365240%28v=vs.85%29.aspx)
> if the flag **MOVEFILE_REPLACE_EXISTING** is used and target already
> exists.
> 
> ---
> 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/untitaker/python-atomicwrites/issues/12#issuecomment-236817294

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.
