### ISSUE TITLE
Proper fsync on Windows

### ISSUE THREAD

**Issue by untitaker** [untitaker/python-atomicwrites#18]
See #6. [This blogpost](http://blog.httrack.com/blog/2013/11/15/everything-you-always-wanted-to-know-about-fsync/) covers this issue in great detail. For Windows, this is mentioned:

> On Windows, using FlushFileBuffers() is probably the way to go.

Not really a confident statement, more research needed.

**Comment by untitaker** [comment]
We currently use [_commit](https://msdn.microsoft.com/en-us/library/17618685.aspx), which doesn't try to flush disk buffers. However, there is no indication that [FlushFileBuffers](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364439%28v=vs.85%29.aspx) is different in that regard.

**Comment by Dobatymo** [comment]
First: `_commit` calls `FlushFileBuffers` internally (according to https://stackoverflow.com/a/1947818). Second: Where do you actually call `_commit`?

**Comment by untitaker** [comment]
`os.fsync` is documented as calling `_commit`. I guess then this issue is not actionable
