### ISSUE TITLE
Please provide a CHANGES file

### ISSUE THREAD

**Issue by 0-wiz-0** [untitaker/python-atomicwrites#22]
Very helpful for packagers, interesting for some other people.

**Comment by untitaker** [comment]
Forgot to reply, I will do this once there are significant changes.

**Comment by adamchainz** [comment]
+1 I just came here when upgrading from 1.1.5 to 1.2.1, it's not immediately obvious what the change is. I can't find a '1.2.0' commit either.

See https://keepachangelog.com/en/1.0.0/ for some advice.

Thanks for a great library.

**Comment by untitaker** [comment]
@adamchainz there is no intentional API breakage between 0.1 and 0.2.

0.2.0's sdist unintentionally contained additional pyc files, which is why 0.2.1 exists.

Yeah, eventually a CHANGELOG will exist.

**Comment by adamchainz** [comment]
Thanks for clarifying

**Comment by rrueth** [comment]
Thanks for all of the work, @untitaker!  I also found my way to this issue this morning when our dependency management tool (e.g. dependencies.io, pyup, etc.) notified us of the update.  The changelog is really helpful as these tools will pull in the changes into a PR and makes it easy for us to assess the update.

**Comment by untitaker** [comment]
Given the low activity on this project I think it would make sense to convert the commit log into a changelog, because to be honest I don't care enough about making a real one.

**Comment by untitaker** [comment]
I decided not to do this. This project has had no breaking changes, is unlikely to ever have some and has less than 5 commits per release. Just read the commit log.
