### ISSUE TITLE
Use os.replace instead of os.rename for python 3.3+

### ISSUE THREAD

**Issue by dhulke** [untitaker/python-atomicwrites#25]
I'm using this lib on Windows 10 with no issues so far, but I'm affraid os.rename, though not well documented for Windows, isn't atomic. As per the documentation:

> If you want cross-platform overwriting of the destination, use replace().
https://docs.python.org/3/library/os.html#os.rename

So I suggest something along the lines of:

```
def _replace_atomic(src, dst):
        try:
                os.replace(src, dst)
        except:
                os.rename(src, dst)
        _sync_directory(os.path.normpath(os.path.dirname(dst)))
```

Ill submit a pull request and I would appreciate if you could update your pip entry. Thanks

**Comment by untitaker** [comment]
This library doesn't use os.rename for Windows.

**Comment by dhulke** [comment]
I actually misread the code and assumed sys.platform was only meant for 32bit systems, which is not the case. My bad. Nonetheless, as per the documentation, os.replace should be used whenever available for cross platform atomic replacement.  So i suggest we try using os.replace for all platforms and when not available, make the distinction between win32 and os.rename as done in this code sample: http://code.activestate.com/recipes/579097-safely-and-atomically-write-to-a-file/

Ill fix the code and propose a new pull request

**Comment by untitaker** [comment]
On Windows: That's not really possible for the case where atomicwrites should fail when the target file already exists. For that you need to use the winapi directly.

On Unix: Could be possible to use for the other case, yes.

I suggest that you look at the strace output of a test script to see which system calls are used. In the end those have to be atomic.

**Comment by dhulke** [comment]
On Windows I think that's the case only for Python 3.2 and lower. I've found quite a few sources for that and I have tested os.replace on Windows myself and it worked. A few good sources:

http://stupidpythonideas.blogspot.com.br/2014/07/getting-atomic-writes-right.html
http://code.activestate.com/recipes/579097-safely-and-atomically-write-to-a-file/
and of course the documentation stating it's cross platform:
https://docs.python.org/3/library/os.html#os.replace

So I would think that it is better to trust os.replace whenever available and only fallback to either os.rename or winapi when necessary. Would you agree?

**Comment by untitaker** [comment]
I don't doubt the atomicity of os.replace, but rather doubt that it's the
correct behavior when you want to ensure you error our when the target file
exists. That's why I am using Winapi.

I don't think there's any point in special-casing use of os.replace. It does
the same thing under the hood as far as I can tell and is not available for
lower Python versions. That means we'd not simplify code but only add another
codepath which is used some of the time with no clear benefits.

**Comment by dhulke** [comment]
When I said I tested on Windows, I meant to say I tested it when target file already exists and it worked. So it's not only an additional code path, but one that simplifies/solidifies cross platform support

**Comment by untitaker** [comment]
Regardless of that it's still not a single codepath since I need to support
older Python versions as well.

Also note that we have two variants for each platform, because the user can
configure whether an existing destination file should be overwritten or not.

**Comment by dhulke** [comment]
So you would rather have dubious winapi calls for modern python interpreters than make special functions that arent even in your AtomicWriter? Really? And obviously going against every modern atomic write example on the web for both posix and win32?

**Comment by untitaker** [comment]
I don't think you understand what I previously said about the extra functionality I need from this library, or that you have read the README where I explained why Andrew Barnert's fatomic library (to which you linked previously) doesn't do everything that I need.

No, I don't use ctypes just because it's fun. I'd like to get rid of it. If you can do that without making the code even messier, make a PR. But I don't think you understand the reason why this library exists. If the code from activestate really did what I wanted to do, why would I have written this library like it is?

**Comment by dhulke** [comment]
I'm not sure we're looking at the same README, but you haven't explained why specifically fatomic isn't sufficient for your needs. Fatomic takes care of all of them, as os.replace/os.rename can both handle existent target and error handling is handled just as well as you do. The reason why I don't use fatomic/activestate is because they don't handle src/dst directory synchronization and so I'm not sure the file has made it to disk after leaving the context manager. The activestate solution also doesn't do a good job on providing a good win32 fallback for older python versions.

The overwrite functionality isn't a big deal for me, though. The main reason I'm using this lib is because it's the only one that does the job right.

Maybe I have been misunderstood, I'm not advocating for the removal of ctypes, I don't even think there is a Python2/3 self contained cross platform solution without them. I'm specifically advocating for the use of os.replace whenever possible so as to comply with current python documentation. It is worth noting that MoveFileExW is not guaranteed to be atomic as per a few sources on the web. So if we have to choose between a dubious win32 api and a modern module that the documentation states is atomic and cross platform, I would think the discussion is over. The right choice seems to be pretty obvious.

It's really no big deal for me to add `git+https://github.com/dhulke/python-atomicwrites.git#egg=atomicwrites` to my requirements.txt and fix this on my own repository. The reason why I'm arguing here is just so I'm 100% sure I'm not missing anything else like I did on my first PR. So if you're telling me you don't want to default to os.replace just because it'll add an additional codepath and the code wont look prettier and you'd rather have dubious but prettier code than to have a solid and "by the book" but longer code, then that would be enough for me and I would just use my own repository.

**Comment by untitaker** [comment]
- os.replace calls MoveFileExW (which is just the unicode version of
  MoveFileEx) with the exact same flags as this library does:
  https://github.com/python/cpython/blob/master/Modules/posixmodule.c

- fatomic calls MoveFileEx with the exact same flags as this library does:
  https://github.com/abarnert/fatomic/blob/master/fatomic.py#L29

- Whether MoveFileEx is atomic is addressed in the README. TLDR: For lack of
  alternatives we use that.

**Comment by dhulke** [comment]
Yeah I actually checked the source for replace/rename and saw that. My point was just to comply with documentation. We don't know whether that's going to change and I would always follow recommendations. But that's ok, I understand I'm pushing this a bit too far. Thank you anyways and congratulations for the amazing module. I'll eventually update my fork and if you're ever interested I can send a PR. Thanks again

**Comment by untitaker** [comment]
I don't get why I would try to "comply" with Python docs. They give us tools but it's always up to us whether we use them.

**Comment by untitaker** [comment]
I don't get why I would try to "comply" with Python docs. They give us tools but it's always up to us whether we use them.

**Comment by dhulke** [comment]
forward compatibility? To have more engaged teams (python developers) worry about cross platform?

**Comment by untitaker** [comment]
If you say so... I'm going to close this issue now though
