### ISSUE TITLE
How do I integrate this with ZipFile?

### ISSUE THREAD

**Issue by MacHu-GWU** [untitaker/python-atomicwrites#31]
This is how we use ZipFile.

```python
src = "a.txt"
dst = "a.zip"

with ZipFile(dst, "w") as f:
    f.write(src)
```

How can I integrate ``atomic_write`` with this?
Could you provide me an example that use ``atomic_write`` to zip a single large text file?

Thank you

**Comment by untitaker** [comment]
Sorry, please use StackOverflow or an official Python support channel for this.
