### ISSUE TITLE
Add `atomic_folder`

### ISSUE THREAD

**Issue by sotte** [untitaker/python-atomicwrites#35]
Sometimes I have a bunch of operations which create many files in a folder. The folder should only be there in the end of the operation. Something like this:
```python
with atomic_folder("foo") as folder:
    unzip(something, folder)
    # "foo/" doesn't exist yet.
# now it does
```

**Comment by untitaker** [comment]
`mkdir` is already atomic though.

**Comment by sotte** [comment]
Yes, but I want the folder "foo" only to exists if the operation (in the example above `unzip`) succeeds. I don't want the result of a partially unpacked zip file.

**Comment by untitaker** [comment]
I guess that makes sense! I am open to PRs

**Comment by sotte** [comment]
I actually have a (buggy) version of the `atomic_folder` that I want to retire in favor of a maintained package. I'll check if I can recycle and contribute this.

**Comment by untitaker** [comment]
Sounds fine to me. I guess it's in the spirit of this package to provide a less buggy one.

**Comment by asottile** [comment]
afaik there isn't a way to make folder rename atomic

```
$ mv --no-target-directory dir1 dir2
mv: cannot move 'dir1' to 'dir2': Directory not empty
```

(you would then need to delete / rename which is always going to race with another process)

The usual trick is to use symlinks:

```bash
mkdir -p _targets/dir1 _targets/dir2
touch _targets/dir1/1 _targets/dir2/2
ln -s "$PWD/_targets/dir1" dir
ln -s "$PWD/_targets/dir2" tmpdir
mv tmpdir dir
```

but symlinks require platform support and sometimes the contents of the directories can be sensitive to their actual location vs the symlinked location

**Comment by untitaker** [comment]
@asottile I think the assumption was to force a value of `overwrite=False` for folders but even then I don't see how this will work out. I'll just close this.
