### ISSUE TITLE
FEAT: file locking

### ISSUE THREAD

**Issue by jbrockmendel** [untitaker/python-atomicwrites#41]
Making file writing atomic is a great feature.  Another feature that might be a good fit is locking files for e.g. appends.

Use Case: I have multiple processes that periodically write (append) to a log file "example_shared_log.txt" and need to prevent them from clobbering each other.  One way to accomplish this is with fcntl:

```
def locked_write(fd, content):
    fcntl.flock(fd, fcntl.LOCK_EX)
    try:
        fd.write(content)
    finally:
        fcntl.flock(fd, fcntl.LOCK_UN)
        fd.close()
```

but that loses atomicity.  A better solution would be to combine a lock on the original path with the rotation that atomicwrites uses.

If I put together a PR, would a feature like this be welcome?

**Comment by untitaker** [comment]
I think it's out of scope for this library, sorry.
