### ISSUE TITLE
Clarify whether Atomicwrites supports Python 3.7

### ISSUE THREAD

**Issue by CAM-Gerlach** [untitaker/python-atomicwrites#43]
Given Python 3.7 has been released well over a year ago and is the default for new versions of most distributions (e.g. Debian 10, Ubuntu 19, Fedora 29, modern Arch, etc.), as well the official Python.org binaries and Anaconda for other platforms, it would be helpful to either run the test suite on Python 3.7 in your tox/travis config and (presuming it passes) declare compatibility in your PyPI Trove classifiers, or else open an issue listing the bug(s) blocking compatibility so you and/or the community can know what to fix (we use it with Spyder on Python 3.7 with no issues, but its possible there could be an edge case the test suite exercises that we do not). If you'd like, I can submit a PR to at least trigger the builds and see if they pass when I get a chance, unless you're aware of issues already. Thanks!

**Comment by untitaker** [comment]
It works on python 3.7! The markers are an oversight.

**Comment by CAM-Gerlach** [comment]
Thanks @untitaker ! I figured that was likely as I'd used it successfully with Python 3.7 myself with Spyder, but seeing that the CI test suite was still running on 3.7 I couldn't be sure. Appreciate your work!
