### ISSUE TITLE
switch from `MoveFileExW` to `MoveFileTransactedW` on windows.

### ISSUE THREAD

**Issue by Cologler** [untitaker/python-atomicwrites#46]
https://docs.microsoft.com/zh-cn/windows/win32/api/winbase/nf-winbase-movefileexw:

> To perform this operation as a transacted operation, use the MoveFileTransacted function.

**Comment by Cologler** [comment]
I found some comment in https://stackoverflow.com/questions/167414/is-an-atomic-file-rename-with-overwrite-possible-on-windows:

> To the best of my knowledge, if the destination existed and an I/O error occurs during the data copy step, this "original" destination is lost, thus MoveFileEx is not atomic per your requirements. That's why MoveFileTransacted was added later.

Not sure it is true or not.

**Comment by untitaker** [comment]
MoveFileTransacted is deprecated as per its documentation at https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-movefiletransacteda which states that TxF may no longer be available in future versions on Windows.

>To the best of my knowledge, if the destination existed and an I/O error occurs during the data copy step, this "original" destination is lost, thus MoveFileEx is not atomic per your requirements. That's why MoveFileTransacted was added later.

Like with `rename` on Linux there is no real data copying going on in MoveFileEx when destination and target are on the same filesystem (which we somewhat ensure by having the tmpfile be in the same directory as the target path). That doesn't mean it's atomic, but it means that the point in the SO comments is not relevant. It is *highly* relevant if you do `MoveFileEx("C:/...", "D:/...")`, but again, we stay within the same drive and folder.

I generally agree that we do not have good citations for that other than the comment I quoted in the README. I still think it's the best we have.
