### ISSUE TITLE
`pathlib.Path` support

### ISSUE THREAD

**Issue by CosmicHorrorDev** [untitaker/python-atomicwrites#47]
Would it be possible to support passing in `pathlib.Path` for the `path` `atomic_write(path)`?

I noticed that doing so works fine for `PosixPath`s, but fails for `WindowsPath`s from [this CI run](https://github.com/LovecraftianHorror/subwinder/runs/609921794?check_suite_focus=true). This can result in someone breaking cross-platform support without being obvious. I notice that the test follows the same solution I went with where you just cast the `path` to a `str`.

Allowing `atomic_write` to accept `Path`s also helps `atomic_write` behave more like `open` as well which also accepts `Path`s.

I haven't delved too far, but the fix might be as simple as

```python
try:
    from pathlib import Path
    if isinstance(path, Path):
        path = str(path)
except ImportError:
    # Just assume `path` is already a `str`
    pass
```

**Comment by untitaker** [comment]
Sounds fine to me, feel free to open a PR! I don't use pathlib myself and am unlikely to use this myself.

A couple of notes upfront:

* attempt the import at import time only. Avoid attempting the import at every use of the library
* check what `open()` actually does to the path

**Comment by CosmicHorrorDev** [comment]
> * attempt the import at import time only. Avoid attempting the import at every use of the library

Sure, I can just store it in some `bool` like `has_pathlib_support`!

> * check what `open()` actually does to the path

So from poking around a bit it looks like `pathlib.Path` support for `open()` was added in Python 3.6, by using `os.fspath()` ([source here](https://github.com/python/cpython/blob/3.6/Lib/_pyio.py#L164), [PR here](https://github.com/python/cpython/commit/d62548afede899e71e59a2a0b31f19fdf031c560)) which will convert the `Path` to either a string or bytes. From after that point `file` can only be a `str`, `bytes`, or `int` (where the `int` is a file descriptor).

So that leaves one final problem where `pathlib` was added in Python 3.4 while `os.fspath()` was added in Python 3.6 so I could:
1. Follow the technique mentioned above of trying to import `pathlib.Path` and casting the `Path` to a `str` or
2. Check if `hasattr(os, 'fspath')` along with doing the attempted import for `pathlib.Path` in the first option and then following the same technique used by `open`
 
The first method would support Python ^3.4, whereas the second supports Python ^3.6: however, I'm guessing that just the cast is probably brittle in some edge-cases where the path might not be a valid `str`. So I would assume we should follow the second option? It should still be a pretty small change if so.

**Comment by untitaker** [comment]
yeah, I would do this on the mod level:

```python
try:
    from os import fspath
except ImportError:
    fspath = None
```

and in the code:

```python
if fspath is not None:
    x = fspath(x)
```

**Comment by CosmicHorrorDev** [comment]
That works, I'll try to find some time to dig into the library and open a PR over the next couple days!
