### ISSUE TITLE
Support Python 3.8

### ISSUE THREAD

**Issue by jugmac00** [untitaker/python-atomicwrites#50]
Python 3.8 is out for a while, so it would be nice if `atomicwrites` support it.

I ran the tests locally with Python 3.8, no errors, not even a deprecation warning.

If you are ok, I'd create a pull request to add support for Python 3.8.

I'd also clean up the current version mismatches:
```
$ check-python-versions 
setup.py says:              2.7, 3.4, 3.5, 3.6, 3.7
- python_requires says:     2.7, 3.4, 3.5, 3.6, 3.7, 3.8
tox.ini says:               2.7, 3.4, 3.5, 3.6, 3.7, 3.8, PyPy
.travis.yml says:           2.7, 3.4, 3.5, 3.6, 3.7, PyPy

mismatch!
```

Also, I noticed, in `appveyor` you only test up to Python 3.6, and only the 32 bit executables. If you are ok, I'd add also the 64 bit versions.

Thanks for your work!

P.S.: What do you think about dropping support for Python 3.4?

**Comment by untitaker** [comment]
That'd be nice, thanks!
