### ISSUE TITLE
Atomic writes for 3rd-party libraries that only take a filename

### ISSUE THREAD

**Issue by torfsen** [untitaker/python-atomicwrites#54]
I'm trying to understand whether I can use `python-atomicwrites` for ensuring that the writes I do via a 3rd-party library are atomic. Unfortunately, the 3rd-party library only takes a filename (not a file object or a file descriptor). It is my understandig that `AtomicWriter` is of little help in this situation: while I could pass `f.name` to the 3rd-party library, the library would re-open the file with a new file descriptor, so even if the two file descriptors wouldn't interfere (which I'm not sure about) the sync-mechanisms of `AtomicWriter` would apply to the wrong descriptor.

Without access to the file descriptor used by the 3rd-party library we cannot use `os.fsync`. If my understanding is correct, then `os.sync` would achieve the same goal, although with the potential overhead of flushing other files' caches, too (my understanding of low-level disk caching is limited, so feel free to correct me here). Therefore, something like the following would probably be the best one could hope for in this situation:

```python
from contextlib import contextmanager
import os
from pathlib import Path
import tempfile

from atomicwrites import replace_atomic

@contextmanager
def atomic_filename(filename: Path) -> Path:
    with tempfile.NamedTemporaryFile(dir=filename.parent, delete=False) as f:
        f.close()
        temp_filename = Path(f.name)
        try:
            yield temp_filename
            os.sync()  # Force disk write
            replace_atomic(temp_filename, filename)
        except (Exception, SystemExit, KeyboardInterrupt):
            raise
        finally:
            try:
                temp_filename.unlink()
            except Exception:
                # There is nothing that we can do here
                pass

with atomic_filename(Path('foo.txt')) as fn:
    # fn is the temporary filename
    third_party_library.do_some_stuff(fn)
# temporary file has been moved atomically to 'foo.txt'
```
Is my understanding correct, or is there a better way to achieve this via `python-atomicwrites`?

(I'm targeting Linux and have little knowledge of how these things work on other platforms)

**Comment by untitaker** [comment]
I think your understanding is correct, but consider monkeypatching or forking the library to use atomicwrites instead of all of this.

**Comment by torfsen** [comment]
Thanks for your feedback, @untitaker! Good idea to mention monkey-patching and forking -- they won't be useful in my current use case but might be applicable for others who face this situation. For the time being I will use the workaround in the OP.

I think it would be nice if `python-atomicwrite` would offer something like this, although I can understand if you want to keep the focus limited to the current scope. I will leave the issue open to serve as a feature request, but my immediate problem is solved so feel free to close it.

Thanks again for your quick response, and for `python-atomicwrite` in general!

**Comment by untitaker** [comment]
I'm going to close it, will consider if it comes up again.
