### ISSUE TITLE
Choice of encoding?

### ISSUE THREAD

**Issue by oprypin** [untitaker/python-atomicwrites#56]
The documentation says that the lib opens files in `'w'` mode (which is text). I don't see any mention of the encoding, though. Not only is there no explicit default, there isn't even a documented way to choose an encoding. After a long look I finally found a trail showing that one can, in fact, pass the `encoding` parameter: the passthrough `atomic_write(**cls_kwargs)` &rarr; `AtomicWriter(**open_kwargs)` (the latter never mentioned).

The problem with that? Well, most people will probably assume it's UTF-8, but instead it seems to be `getdefaultencoding` (not even sure, it's hard to find). It seems like that will help to perpetuate the problems described at https://www.python.org/dev/peps/pep-0597/#using-the-default-encoding-is-a-common-mistake
So there are 2 (3?) issues I see:
* The default encoding is implicit.
  * It's not documented that it's implicit.
* A way to choose an encoding is not shown.

**Comment by untitaker** [comment]
I added documentation for `**open_kwargs` to fix issue 3 but the implicit encoding part is done consistently with the stdlib/builtin `open`.

This library is concerned with writing files atomically, not with providing a universally better user interface over file writing. As such it chooses consistency with `open()` and general familiarity to Python devs over better defaults.
