### ISSUE TITLE
corruption of commas to semicolon in ORG field

### ISSUE THREAD

**Issue by linsam** [untitaker/python-atomicwrites#8]
If I have an ORG field like

`ORG:Example\, Inc.;North West;Sales`

And modify, it shows up in the editor as

`Organisation : Example, Inc., North West, Sales`

And gets saved as

`ORG:Example;Inc.;North West;Sales`

That is, "Example, Inc." became converted to "Example" with a sub org of "Inc."

**Comment by untitaker** [comment]
This is the wrong issue tracker to post this.

**Comment by linsam** [comment]
Indeed. Could have sworn I was on Khard's project page when I clicked "new issue". Sorry for the spam.
