### ISSUE TITLE
_open except block accidentally raises the inner exception

### ISSUE THREAD

**Issue by sruggier** [untitaker/python-atomicwrites#9]
I'm talking specifically about this code:

```
        except:
            try:
                self.rollback(f)
            except Exception:
                pass
            raise
```

I managed to hit a corner case where rollback throws an exception (f was None at that point), so control flow reached the `raise` statement on the last line. For some reason, this raised the inner exception, not the outer one.

I can submit a patch to fix this: would you prefer a fix that uses the three-argument raise statement, which only works with Python 2, or should I add a dependency on six, and then call six.reraise, so it works with both 2 and 3?

**Comment by untitaker** [comment]
Hello @sruggier,

Wow, people do keep finding bugs in the errorhandling part... thanks for offering a patch. I'd prefer the second option, but additionally to vendor `six.reraise` because it's a trivial amount of code.

**Comment by sruggier** [comment]
Just taking a look at six's source tree, it looks like that trivial amount of code seems to depend on a non-trivial extent of other code in the six module to choose between implementations for Python 2 or 3. I'm also noticing now that even pip depends on six, so a bare virtualenv already comes with it included. Anyone using pip to install atomicwrites outside of a virtualenv will also most likely already have it. Have noticed that, I think depending on six makes the most sense. Are you fine with that?

**Comment by untitaker** [comment]
pip vendors six in the form of `pip._vendor.six`, and I'd rather not import that module.

I'm really not okay with it, I think we can't warrant the dependency for such a small module. I'd rather vendor something like https://github.com/mitsuhiko/werkzeug/blob/master/werkzeug/_compat.py

**Comment by untitaker** [comment]
Concretely, https://github.com/mitsuhiko/werkzeug/blob/master/werkzeug/_compat.py#L36 for Python 2 and https://github.com/mitsuhiko/werkzeug/blob/master/werkzeug/_compat.py#L135 for Python 3.

**Comment by sruggier** [comment]
I had just finished making a file with just reraise in it when I remembered that I could avoid the need to reraise by switching to try/finally instead. I've implemented a fix and added a test that catches the original problem, which I'll submit in a PR shortly.
